### PR TITLE
Upgraded BuildTools and Added a beginner friendly note taking application.

### PR DESCRIPTION
**Pull request by navi25**
I believe Note Taking Application is simple enough application for any new person to start with Android development while at the same time it teaches the important features and principles of Andorid development.

Tasks completed:
 - Updated BuildTools and removed unused files
 - Added a simple note taking application with local storage.
 
Pending Tasks:
- Adding a step-by-step tutorial for the application.
- AudioNotes using Google Speech API
- ImageNotes using Camera API

### CODE REVIEW

**Comment by 6peterlu** [comment]
Does this PR contain code for voice notes? If so, I can't get it to work on my emulator. If it does not, maybe we should remove the microphone icon on the note entry to reduce confusion.

**Comment by 6peterlu** [comment]
Another thing we can do is just add some links in the readme to the google speech API and list it as a possible extension for hackers to build on!

Otherwise, this looks great.

**Review by 6peterlu — CHANGES_REQUESTED** [review]
Once we clear up the microphone situation, we should be good to go.

**Comment by navi25** [comment]
> Does this PR contain code for voice notes? If so, I can't get it to work on my emulator. If it does not, maybe we should remove the microphone icon on the note entry to reduce confusion.

Currently no, this doesn't contain voice notes and I agree we can remove them to reduce confusion. I will update the view and update the pull request.

**Comment by navi25** [comment]
> Another thing we can do is just add some links in the readme to the google speech API and list it as a possible extension for hackers to build on!
> 
> Otherwise, this looks great.

Great Idea, I will add the links.

**Review by 6peterlu — APPROVED** [review]

**Comment by 6peterlu** [comment]
looks great! thanks a bunch Navendra (:

**Pull request merged**
